name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set Up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version-file: .sdkmanrc
          distribution: temurin
          cache: gradle

      - name: Set Up PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: documentation/package.json

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: documentation/pnpm-lock.yaml

      - name: Assemble
        run: ./gradlew compileAll assemble

      - name: Test
        run: ./gradlew allTests

      - name: Upload Test Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: test-results
          path: '**/build/test-results/'
